version: '3.8'

services:
  api:
    build: .
    ports:
      - "8008:8008"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - decode-network

networks:
  decode-network:
    driver: bridge 